config-version: 1.0.1

# Chest config
# probability = More chances of reaching max-contents filled
#
# max-contents = Maximum number of *slots* filled in a chest (this applies to double chest), not amount of items
# min-contents = Minimum number of *slots* filled in a chest (this applies to double chest), not amount of items
# keep-open = Keep a chest open after opening it for the first time
chest:
  probability: 12
  max-contents: 6
  min-contents: 3
  keep-open: false

# Border config
# Border for the map. Can be disabled. Size is radius from center.
border:
  enabled: false
  size: 500

# Player config
# min-players = Minimum players to start game
# max-players = Maximum players to allow join
# kick-on-death = Kick players on death.
# allow-spectators = Allow spectators to join the match after it started.
# min-deathmatch = Minimum players required to trigger deathmatch.
players:
  min-players: 3
  max-players: 24
  kick-on-death: false
  allow-spectators: true
  min-deathmatch: 3

# Duration config
# starting = Duration for lobby, pre-game and pre-deathmatch.
# grace-period = Duration for grace period.
# running = Duration for normal game until deathmatch
# deathmatch = Duration of deathmatch until game finishes.
# finishing = Duration before closing the server
duration:
  starting: 25s
  grace-period: 15s
  running: 20m
  deathmatch: 10m
  finishing: 10s
  unknown: 0s

# Spawnpoints config
# random = Randomize spawnpoints
spawn:
  random: true

# Effects config
# death-lightning = Strike lightning when a game dies (will not harm)
# win-fireworks = Launch fireworks at spawnpoint and around winner
# win-set-night = Set the map to night when win
# dm-set-night = Set the map to night when deathmatch starts
effects:
  death-lightning: true
  win-fireworks: true
  win-set-night: true
  dm-set-night: true

# Setup mode. This will disable matchmaking and enable map creation.
setup-mode: true

messages:
  # {victim} to show victim
  # {killer} to show killer
  kill: "&6A cannon could be heard in the distance."
  died: "&cYou died!"

  # {time} to show time (e.g. 30s)
  # {winner} to show winner
  ready: "&aThe game is ready to start!"
  starting: "&aThe game is starting in {time}"
  start: "&aThe game has started! Good luck!"
  grace-period: "&bGrace period will end in {time}"
  grace-period-end: "&bGrace period has ended! PvP is now enabled!"
  until-deathmatch: "&cDeathmatch will start in {time}"
  deathmatch: "&cDeathmatch will end in {time}"
  finish: "&cThe game has finished! Returning in {time}"
  game-started: "&cThe game has already started!"
  full: "&cThe game is already full!"
  spectate-prefix: "&7[SPECTATING] "
  winner: "&a{winner} has won the &6Hunger Games!"
  time-remaining: "&aTime Remaining: &e{time}"
  unknown: "Unknown"

  duration:
    second: "s"
    minute: "m"
    hour: "h"
