name: SGames
version: '${project.version}'
main: xyz.destiall.sgames.SGames
api-version: 1.17
author: destiall
description: Survival Games for SGCraft
softdepend: [ PlaceholderAPI ]
commands:
  sgames:
    aliases: [sg]
